// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqXlnPgX-SvWyLb1lX-XSd2wWVY8jhlX8',
    appId: '1:965650301921:web:b33f72b79e52a3275848a0',
    messagingSenderId: '965650301921',
    projectId: 'pim-sim',
    authDomain: 'pim-sim.firebaseapp.com',
    storageBucket: 'pim-sim.appspot.com',
    measurementId: 'G-ZTH95KK5ZN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5TgLRNN58P97l5yKRXkPL9MnTfy_hqdY',
    appId: '1:965650301921:android:482a0c6e3e5a40f25848a0',
    messagingSenderId: '965650301921',
    projectId: 'pim-sim',
    storageBucket: 'pim-sim.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpUvQdy1Mj5-K3ItIN8qbKWZNFxtVNcCo',
    appId: '1:965650301921:ios:ba8bf291091975955848a0',
    messagingSenderId: '965650301921',
    projectId: 'pim-sim',
    storageBucket: 'pim-sim.appspot.com',
    iosBundleId: 'com.example.flutterNodeAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpUvQdy1Mj5-K3ItIN8qbKWZNFxtVNcCo',
    appId: '1:965650301921:ios:ba8bf291091975955848a0',
    messagingSenderId: '965650301921',
    projectId: 'pim-sim',
    storageBucket: 'pim-sim.appspot.com',
    iosBundleId: 'com.example.flutterNodeAuth',
  );
}
